trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '8e14991b-40e5-44af-beaf-596718444ca7'

  # Web app name
  webAppName: 'my-app-freddy'

  # Environment name
  environmentName: 'my-app-freddy'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        echo "##vso[task.setvariable variable=JAVA_HOME]$(dirname $(dirname $(readlink -f $(which java))))"
        echo "##vso[task.prependpath]$(dirname $(dirname $(readlink -f $(which javac))))/bin"
      displayName: 'Set up Java 17'

    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'  # Asegúrate de limpiar y empaquetar

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1  # Correct task name
      displayName: 'Publish Artifact'
      inputs:
        artifactName: 'drop'
        pathToPublish: '$(Build.ArtifactStagingDirectory)'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1  # Correct task name
            displayName: 'Azure Web App Deploy: $(webAppName)'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Build.ArtifactStagingDirectory)/**/*.war'  # O *.jar dependiendo de tu proyecto





